"""add players and squad_values

Revision ID: 396d24a49ad7
Revises: 42af0f968a5c
Create Date: 2026-07-04 22:14:46.340867

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "396d24a49ad7"
down_revision: str | Sequence[str] | None = "42af0f968a5c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tm_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.String(), nullable=False),
        sa.Column("market_value_eur", sa.BigInteger(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tm_id"),
    )
    op.create_index(op.f("ix_players_name"), "players", ["name"], unique=False)
    op.create_index(op.f("ix_players_team_id"), "players", ["team_id"], unique=False)
    op.create_table(
        "squad_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season", sa.String(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("value_eur", sa.BigInteger(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season", "team_id", name="uq_squad_value_season_team"),
    )
    op.create_index(op.f("ix_squad_values_season"), "squad_values", ["season"], unique=False)
    op.create_index(op.f("ix_squad_values_team_id"), "squad_values", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_squad_values_team_id"), table_name="squad_values")
    op.drop_index(op.f("ix_squad_values_season"), table_name="squad_values")
    op.drop_table("squad_values")
    op.drop_index(op.f("ix_players_team_id"), table_name="players")
    op.drop_index(op.f("ix_players_name"), table_name="players")
    op.drop_table("players")
    # ### end Alembic commands ###
