"""add fixtures table

Revision ID: 42af0f968a5c
Revises: 60d23bc4d0b1
Create Date: 2026-07-04 00:44:14.855944

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42af0f968a5c"
down_revision: str | Sequence[str] | None = "60d23bc4d0b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fixtures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season", sa.String(), nullable=False),
        sa.Column("matchday", sa.Integer(), nullable=False),
        sa.Column("kickoff_utc", sa.DateTime(), nullable=False),
        sa.Column("home_id", sa.Integer(), nullable=False),
        sa.Column("away_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "season", "matchday", "home_id", "away_id", name="uq_fixture_season_md_home_away"
        ),
    )
    op.create_index(op.f("ix_fixtures_away_id"), "fixtures", ["away_id"], unique=False)
    op.create_index(op.f("ix_fixtures_home_id"), "fixtures", ["home_id"], unique=False)
    op.create_index(op.f("ix_fixtures_kickoff_utc"), "fixtures", ["kickoff_utc"], unique=False)
    op.create_index(op.f("ix_fixtures_season"), "fixtures", ["season"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fixtures_season"), table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_kickoff_utc"), table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_home_id"), table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_away_id"), table_name="fixtures")
    op.drop_table("fixtures")
    # ### end Alembic commands ###
