"""add model_runs and team_params

Revision ID: 89302ee3bc50
Revises: eb47dc806305
Create Date: 2026-06-15 21:50:54.145947

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89302ee3bc50"
down_revision: str | Sequence[str] | None = "eb47dc806305"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trained_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("model_type", sa.String(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("xi", sa.Float(), nullable=False),
        sa.Column("rho", sa.Float(), nullable=False),
        sa.Column("home_adv", sa.Float(), nullable=False),
        sa.Column("log_likelihood", sa.Float(), nullable=False),
        sa.Column("n_matches", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_runs_as_of_date"), "model_runs", ["as_of_date"], unique=False)
    op.create_table(
        "team_params",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_run_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("attack", sa.Float(), nullable=False),
        sa.Column("defense", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_run_id"],
            ["model_runs.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_run_id", "team_id", name="uq_team_param_run_team"),
    )
    op.create_index(
        op.f("ix_team_params_model_run_id"), "team_params", ["model_run_id"], unique=False
    )
    op.create_index(op.f("ix_team_params_team_id"), "team_params", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_params_team_id"), table_name="team_params")
    op.drop_index(op.f("ix_team_params_model_run_id"), table_name="team_params")
    op.drop_table("team_params")
    op.drop_index(op.f("ix_model_runs_as_of_date"), table_name="model_runs")
    op.drop_table("model_runs")
    # ### end Alembic commands ###
