"""create teams, team_aliases, matches

Revision ID: c43fb31ecba5
Revises:
Create Date: 2026-06-15 04:57:32.479269

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c43fb31ecba5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tm_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("tm_id"),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("home_id", sa.Integer(), nullable=False),
        sa.Column("away_id", sa.Integer(), nullable=False),
        sa.Column("home_goals", sa.Integer(), nullable=False),
        sa.Column("away_goals", sa.Integer(), nullable=False),
        sa.Column("ftr", sa.String(), nullable=False),
        sa.Column("ht_home_goals", sa.Integer(), nullable=True),
        sa.Column("ht_away_goals", sa.Integer(), nullable=True),
        sa.Column("htr", sa.String(), nullable=True),
        sa.Column("home_shots", sa.Integer(), nullable=True),
        sa.Column("away_shots", sa.Integer(), nullable=True),
        sa.Column("home_sot", sa.Integer(), nullable=True),
        sa.Column("away_sot", sa.Integer(), nullable=True),
        sa.Column("home_fouls", sa.Integer(), nullable=True),
        sa.Column("away_fouls", sa.Integer(), nullable=True),
        sa.Column("home_corners", sa.Integer(), nullable=True),
        sa.Column("away_corners", sa.Integer(), nullable=True),
        sa.Column("home_yellows", sa.Integer(), nullable=True),
        sa.Column("away_yellows", sa.Integer(), nullable=True),
        sa.Column("home_reds", sa.Integer(), nullable=True),
        sa.Column("away_reds", sa.Integer(), nullable=True),
        sa.Column("b365_home", sa.Float(), nullable=True),
        sa.Column("b365_draw", sa.Float(), nullable=True),
        sa.Column("b365_away", sa.Float(), nullable=True),
        sa.Column("avg_home", sa.Float(), nullable=True),
        sa.Column("avg_draw", sa.Float(), nullable=True),
        sa.Column("avg_away", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["away_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season", "home_id", "away_id", name="uq_match_season_home_away"),
    )
    op.create_index(op.f("ix_matches_away_id"), "matches", ["away_id"], unique=False)
    op.create_index(op.f("ix_matches_date"), "matches", ["date"], unique=False)
    op.create_index(op.f("ix_matches_home_id"), "matches", ["home_id"], unique=False)
    op.create_index(op.f("ix_matches_season"), "matches", ["season"], unique=False)
    op.create_table(
        "team_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_aliases")
    op.drop_index(op.f("ix_matches_season"), table_name="matches")
    op.drop_index(op.f("ix_matches_home_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_date"), table_name="matches")
    op.drop_index(op.f("ix_matches_away_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_table("teams")
    # ### end Alembic commands ###
