"""add understat xg to matches and xg_coef to model_runs

Revision ID: dfeb2f438d50
Revises: 396d24a49ad7
Create Date: 2026-07-07 14:41:38.430913

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfeb2f438d50"
down_revision: str | Sequence[str] | None = "396d24a49ad7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("home_xg", sa.Float(), nullable=True))
    op.add_column("matches", sa.Column("away_xg", sa.Float(), nullable=True))
    op.add_column(
        "model_runs", sa.Column("xg_coef", sa.Float(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_runs", "xg_coef")
    op.drop_column("matches", "away_xg")
    op.drop_column("matches", "home_xg")
    # ### end Alembic commands ###
