"""add closing 1x2 odds to matches

Revision ID: eb47dc806305
Revises: c43fb31ecba5
Create Date: 2026-06-15 21:48:16.613586

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb47dc806305"
down_revision: str | Sequence[str] | None = "c43fb31ecba5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("b365c_home", sa.Float(), nullable=True))
    op.add_column("matches", sa.Column("b365c_draw", sa.Float(), nullable=True))
    op.add_column("matches", sa.Column("b365c_away", sa.Float(), nullable=True))
    op.add_column("matches", sa.Column("avgc_home", sa.Float(), nullable=True))
    op.add_column("matches", sa.Column("avgc_draw", sa.Float(), nullable=True))
    op.add_column("matches", sa.Column("avgc_away", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "avgc_away")
    op.drop_column("matches", "avgc_draw")
    op.drop_column("matches", "avgc_home")
    op.drop_column("matches", "b365c_away")
    op.drop_column("matches", "b365c_draw")
    op.drop_column("matches", "b365c_home")
    # ### end Alembic commands ###
