"""Guard that Alembic migrations and the ORM models stay in sync.

Runs the full migration chain against a fresh Postgres and asserts there's no
pending autogenerate diff. If a later phase adds a column/table to the models
without a matching migration, this fails.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from testcontainers.postgres import PostgresContainer

ROOT = Path(__file__).resolve().parents[2]


def _alembic_config(url: str) -> Config:
    cfg = Config(str(ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(ROOT / "alembic"))
    cfg.set_main_option("sqlalchemy.url", url)
    return cfg


def test_migrations_match_models(monkeypatch: pytest.MonkeyPatch) -> None:
    with PostgresContainer("postgres:16", driver="psycopg") as postgres:
        url = postgres.get_connection_url()
        # env.py reads DATABASE_URL; point it at this throwaway container.
        monkeypatch.setenv("DATABASE_URL", url)
        cfg = _alembic_config(url)

        command.upgrade(cfg, "head")
        try:
            command.check(cfg)
        except AutogenerateDiffsDetected as exc:
            pytest.fail(f"models drifted from migrations: {exc}")
